const IdentifierBody = /^[0-9A-HJKMNP-TV-Z]{26}$/;
/* New-style customer identifiers are `customer_<canonical lowercase UUID>`
   (RFC 4122, as generated by crypto.randomUUID). The legacy 26-character
   Crockford base32 body remains valid so existing ledgers, grants, and export
   bundles keep parsing. */
const CustomerUuidBody = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
type Brand<T, Name extends string> = T & { readonly __brand: Name };

export type CustomerId = Brand<string, "CustomerId">;
export type CaseId = Brand<string, "CaseId">;
export type GrantId = Brand<string, "GrantId">;
export type DumpId = Brand<string, "DumpId">;
export type AuditEventId = Brand<string, "AuditEventId">;
export type IdentifierKind = "customer" | "case" | "grant" | "dump" | "audit";

function parseIdentifier<Id extends string>(value: unknown, prefix: string, label: string): Id {
  if (typeof value !== "string") throw new TypeError(`invalid ${label} identifier`);
  const body = value.slice(prefix.length + 1);
  if (!value.startsWith(`${prefix}_`) || !IdentifierBody.test(body)) {
    throw new TypeError(`invalid ${label} identifier`);
  }
  return value as Id;
}

export const parseCustomerId = (value: unknown): CustomerId => {
  if (typeof value !== "string") throw new TypeError("invalid customer identifier");
  const body = value.slice("customer".length + 1);
  if (!value.startsWith("customer_") || (!IdentifierBody.test(body) && !CustomerUuidBody.test(body))) {
    throw new TypeError("invalid customer identifier");
  }
  return value as CustomerId;
};
export const parseCaseId = (value: unknown): CaseId => parseIdentifier(value, "case", "case");
export const parseGrantId = (value: unknown): GrantId => parseIdentifier(value, "grant", "grant");
export const parseDumpId = (value: unknown): DumpId => parseIdentifier(value, "dump", "dump");
export const parseAuditEventId = (value: unknown): AuditEventId => parseIdentifier(value, "audit", "audit event");

export interface IdSource {
  next(kind: "customer"): CustomerId;
  next(kind: "case"): CaseId;
  next(kind: "grant"): GrantId;
  next(kind: "dump"): DumpId;
  next(kind: "audit"): AuditEventId;
}

export function parseGeneratedId(kind: IdentifierKind, value: unknown): string {
  switch (kind) {
    case "customer": return parseCustomerId(value);
    case "case": return parseCaseId(value);
    case "grant": return parseGrantId(value);
    case "dump": return parseDumpId(value);
    case "audit": return parseAuditEventId(value);
  }
}
