import assert from "node:assert/strict";
import { describe,it } from "node:test";
import { fixture,createQuarantined } from "./support.js";
describe("lifecycle engine",()=>{
  it("publishes only a case-bound validated vault object",()=>{const{engine,vault}=fixture();const id=createQuarantined(engine,vault);assert(engine.execute({type:"AcceptDump",dumpId:id}).ok);const dump=engine.snapshot().dumps[0];assert.equal(dump?.phase,"available");assert.equal(dump?.coverage,"partial");assert.equal(dump?.downloadable,true);assert.deepEqual(engine.integrityCheck(),[]);engine.close();});
  it("rejects illegal transitions without partial mutation",()=>{const{engine,vault}=fixture();const customer=engine.execute({type:"CreateCustomer",displayName:"Acme"});assert(customer.ok&&customer.customerId);const c=engine.execute({type:"CreateCase",customerId:customer.customerId,title:"x"});assert(c.ok&&c.caseId);const g=engine.execute({type:"IssueGrant",caseId:c.caseId,expiresAt:"2026-09-05T00:00:00.000Z",maxBytes:8n});assert(g.ok&&g.grantSecret);const b=engine.execute({type:"BeginUpload",grantSecret:g.grantSecret,originalName:"x"});assert(b.ok&&b.dumpId);const before=engine.snapshot();const bad=engine.execute({type:"PromoteObject",dumpId:b.dumpId});assert(!bad.ok);assert.equal(bad.error.code,"invalid_transition");assert.deepEqual(engine.snapshot(),before);assert.deepEqual(vault.inspectPresence(b.dumpId),{staging:true,vault:false});engine.close();});
  it("consumes each grant at most once",()=>{const{engine,vault}=fixture();const customer=engine.execute({type:"CreateCustomer",displayName:"Acme"});assert(customer.ok&&customer.customerId);const c=engine.execute({type:"CreateCase",customerId:customer.customerId,title:"x"});assert(c.ok&&c.caseId);const g=engine.execute({type:"IssueGrant",caseId:c.caseId,expiresAt:"2026-09-05T00:00:00.000Z",maxBytes:8n});assert(g.ok&&g.grantSecret);const first=engine.execute({type:"BeginUpload",grantSecret:g.grantSecret,originalName:"one"});assert(first.ok);const second=engine.execute({type:"BeginUpload",grantSecret:g.grantSecret,originalName:"two"});assert(!second.ok);assert.equal(second.error.code,"grant_consumed");assert.equal(engine.snapshot().dumps.length,1);assert.equal(vault.listStagingIds().length,1);engine.close();});
  it("preserves association and disables download in tombstone",()=>{const{engine,vault}=fixture();const id=createQuarantined(engine,vault);assert(engine.execute({type:"AcceptDump",dumpId:id}).ok);const caseId=engine.snapshot().dumps[0]?.caseId;assert(engine.execute({type:"BeginPurge",dumpId:id}).ok);assert(engine.execute({type:"FinishPurge",dumpId:id}).ok);const dump=engine.snapshot().dumps[0];assert.equal(dump?.phase,"deleted");assert.equal(dump?.caseId,caseId);assert.equal(dump?.downloadable,false);engine.close();});
});
