import assert from "node:assert/strict";
import { describe,it } from "node:test";
import { ScriptedFailpoints,createDumpLedgerEngine,DeterministicClock,DeterministicEntropy,DeterministicIds } from "../../src/engine/dump-ledger-engine.js";
import { reconcile } from "../../src/recovery/reconcile.js";
import { MemoryVault } from "../../src/vault/memory-vault.js";
import { createQuarantined,fixture,Timestamp } from "./support.js";
function crashing(vault:MemoryVault,points:ConstructorParameters<typeof ScriptedFailpoints>[0]){return createDumpLedgerEngine({databasePath:":memory:",vault,inspection:{inspect:()=>({ok:true,coverage:"unknown",facts:{}})},grantSecretKey:new Uint8Array(32),clock:new DeterministicClock(Timestamp),entropy:new DeterministicEntropy(["s".repeat(43)]),ids:new DeterministicIds(),failpoints:new ScriptedFailpoints(points)});}
describe("startup reconciliation",()=>{
  it("removes only aged orphan staging",()=>{const vault=new MemoryVault(()=>1000),{engine}=fixture(undefined,vault);const id=(new DeterministicIds()).next("dump");vault.createStaging(id);assert.equal(reconcile(engine,vault,{nowMs:1500,orphanGraceMs:1000}).actions.length,0);assert.equal(vault.inspectPresence(id).staging,true);assert.equal(reconcile(engine,vault,{nowMs:2000,orphanGraceMs:1000}).actions[0]?.outcome,"orphan-removed");engine.close();});
  it("recovers a crash after staging creation without inventing a dump",()=>{const vault=new MemoryVault(()=>1000),engine=crashing(vault,["after_staging_create"]);const customer=engine.execute({type:"CreateCustomer",displayName:"A"});assert(customer.ok&&customer.customerId);const c=engine.execute({type:"CreateCase",customerId:customer.customerId,title:"x"});assert(c.ok&&c.caseId);const g=engine.execute({type:"IssueGrant",caseId:c.caseId,expiresAt:"2026-09-05T00:00:00.000Z",maxBytes:4n});assert(g.ok&&g.grantSecret);const secret=g.grantSecret;assert.throws(()=>engine.execute({type:"BeginUpload",grantSecret:secret,originalName:"x"}),/simulated crash/);assert.equal(engine.snapshot().dumps.length,0);reconcile(engine,vault,{nowMs:2000,orphanGraceMs:1000});assert.equal(vault.listStagingIds().length,0);engine.close();});
  it("marks interrupted receiving transfer failed",()=>{const{engine,vault}=fixture();const customer=engine.execute({type:"CreateCustomer",displayName:"A"});assert(customer.ok&&customer.customerId);const c=engine.execute({type:"CreateCase",customerId:customer.customerId,title:"x"});assert(c.ok&&c.caseId);const g=engine.execute({type:"IssueGrant",caseId:c.caseId,expiresAt:"2026-09-05T00:00:00.000Z",maxBytes:4n});assert(g.ok&&g.grantSecret);const b=engine.execute({type:"BeginUpload",grantSecret:g.grantSecret,originalName:"x"});assert(b.ok&&b.dumpId);vault.append(b.dumpId,Uint8Array.of(1));reconcile(engine,vault);assert.equal(engine.snapshot().dumps[0]?.validation,"transfer-failed");assert.deepEqual(vault.inspectPresence(b.dumpId),{staging:false,vault:false});engine.close();});
  it("recovers filesystem promotion before ledger commit",()=>{const vault=new MemoryVault(),engine=crashing(vault,["after_vault_promote"]);const id=createQuarantinedPrelude(engine,vault);assert.throws(()=>engine.execute({type:"PromoteObject",dumpId:id}),/simulated crash/);assert.equal(engine.snapshot().dumps[0]?.blobState,"staging");assert.equal(reconcile(engine,vault).actions[0]?.outcome,"available");engine.close();});
  it("recovers committed promotion before quarantine",()=>{const{engine,vault}=fixture();const id=createQuarantinedPrelude(engine,vault);assert(engine.execute({type:"PromoteObject",dumpId:id}).ok);assert.equal(engine.snapshot().dumps[0]?.blobState,"vault");assert.equal(reconcile(engine,vault).actions[0]?.outcome,"available");engine.close();});
  it("finishes deletion interrupted after byte removal",()=>{const vault=new MemoryVault(),engine=crashing(vault,["after_vault_remove"]);const id=createQuarantined(engine,vault);assert(engine.execute({type:"AcceptDump",dumpId:id}).ok);assert(engine.execute({type:"BeginPurge",dumpId:id}).ok);assert.throws(()=>engine.execute({type:"FinishPurge",dumpId:id}),/simulated crash/);reconcile(engine,vault);assert.equal(engine.snapshot().dumps[0]?.phase,"deleted");engine.close();});
});
function createQuarantinedPrelude(engine:ReturnType<typeof createDumpLedgerEngine>,vault:MemoryVault){const customer=engine.execute({type:"CreateCustomer",displayName:"A"});assert(customer.ok&&customer.customerId);const c=engine.execute({type:"CreateCase",customerId:customer.customerId,title:"x"});assert(c.ok&&c.caseId);const g=engine.execute({type:"IssueGrant",caseId:c.caseId,expiresAt:"2026-09-05T00:00:00.000Z",maxBytes:4n});assert(g.ok&&g.grantSecret);const b=engine.execute({type:"BeginUpload",grantSecret:g.grantSecret,originalName:"x"});assert(b.ok&&b.dumpId);vault.append(b.dumpId,Uint8Array.of(1));vault.syncAndClose(b.dumpId);assert(engine.execute({type:"SealUpload",dumpId:b.dumpId,byteSize:1n,sha256:"a".repeat(64)}).ok);return b.dumpId;}
