import assert from "node:assert/strict";
import { describe,it } from "node:test";
import { runRetention } from "../../src/recovery/retention.js";
import { MemoryVault } from "../../src/vault/memory-vault.js";
import { createQuarantined,fixture,Timestamp } from "./support.js";
describe("retention",()=>{
  it("sets only explicit future retention on accepted dumps",()=>{const{engine,vault}=fixture();const id=createQuarantined(engine,vault);assert(engine.execute({type:"AcceptDump",dumpId:id}).ok);assert(engine.execute({type:"SetRetention",dumpId:id,purgeAt:"2026-09-10T00:00:00.000Z"}).ok);assert.equal(engine.snapshot().dumps[0]?.purgeAt,"2026-09-10T00:00:00.000Z");const before=engine.snapshot();const bad=engine.execute({type:"SetRetention",dumpId:id,purgeAt:Timestamp});assert(!bad.ok);assert.equal(bad.error.code,"invalid_input");assert.deepEqual(engine.snapshot(),before);engine.close();});
  it("purges due objects without resurrection",()=>{const{clock,engine,vault}=fixture();const id=createQuarantined(engine,vault);assert(engine.execute({type:"AcceptDump",dumpId:id}).ok);assert(engine.execute({type:"SetRetention",dumpId:id,purgeAt:"2026-09-06T00:00:00.000Z"}).ok);assert.deepEqual(engine.dueForPurge("2026-09-05T23:59:59.999Z"),[]);clock.set("2026-09-06T00:00:00.000Z");assert.deepEqual(runRetention(engine).results,[{dumpId:id,ok:true,phase:"deleted"}]);assert.deepEqual(runRetention(engine).results,[]);assert.deepEqual(vault.inspectPresence(id),{staging:false,vault:false});engine.close();});
  it("exports JSON-safe metadata without claiming vault bytes",()=>{const{engine,vault}=fixture({inspect:()=>({ok:false,error:"invalid"})});const id=createQuarantined(engine,vault);assert(engine.execute({type:"RejectDump",dumpId:id}).ok);assert(engine.execute({type:"SetRetention",dumpId:id,purgeAt:"2026-09-10T00:00:00.000Z"}).ok);const inventory=engine.backupInventory();assert.equal(inventory.includesVaultBytes,false);assert.equal(inventory.dumps[0]?.byteSize,"4");assert.doesNotThrow(()=>JSON.stringify(inventory));engine.close();});
  it("bounds each tick",()=>{const{clock,engine,vault}=fixture();const a=createQuarantined(engine,vault);assert(engine.execute({type:"AcceptDump",dumpId:a}).ok);assert(engine.execute({type:"SetRetention",dumpId:a,purgeAt:"2026-09-06T00:00:00.000Z"}).ok);const b=createQuarantined(engine,vault);assert(engine.execute({type:"AcceptDump",dumpId:b}).ok);assert(engine.execute({type:"SetRetention",dumpId:b,purgeAt:"2026-09-06T00:00:00.000Z"}).ok);clock.set("2026-09-06T00:00:00.000Z");const first=runRetention(engine,undefined,{limit:1});assert.equal(first.results.length,1);assert.equal(first.hasMore,true);const second=runRetention(engine,undefined,{limit:1});assert.equal(second.results.length,1);assert.equal(second.hasMore,false);engine.close();});
  it("retries deleting after a failed finish",()=>{class Flaky extends MemoryVault{private failures=1;override remove(id:Parameters<MemoryVault["remove"]>[0]):void{if(this.failures-->0)throw new Error("fail");super.remove(id);}}const vault=new Flaky(),{clock,engine}=fixture(undefined,vault);const id=createQuarantined(engine,vault);assert(engine.execute({type:"AcceptDump",dumpId:id}).ok);assert(engine.execute({type:"SetRetention",dumpId:id,purgeAt:"2026-09-06T00:00:00.000Z"}).ok);clock.set("2026-09-06T00:00:00.000Z");const first=runRetention(engine);assert.equal(first.results[0]?.ok,false);assert.equal(engine.snapshot().dumps[0]?.phase,"deleting");assert.deepEqual(runRetention(engine).results,[{dumpId:id,ok:true,phase:"deleted"}]);engine.close();});
});
